// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class SevenTestForumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testforum() {
    driver.get("http://www.seventest.com/");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("Valeriya_93");
    driver.findElement(By.name("passwd")).sendKeys("H@ppy#new!year<93>");
    driver.findElement(By.name("Submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .mainmenu > b")).click();
    driver.findElement(By.linkText("Общие вопросы")).click();
  }
}
